name: Build Test with SDK

on: [push, pull_request]

env:
  PERSIST_DIR: /srv/gh-runners/qualcomm-qrb-ros
  DL_DIR: /srv/gh-runners/qualcomm-qrb-ros/downloads
  WORKSPACE: ${{ github.workspace }}/ros_ws
  SDK_DIR: ${{ github.workspace }}/sdk
  QCOM_SELECTED_BSP: custom

jobs:

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      machine: ${{ steps.parse-config.outputs.machine }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install yq

      - name: Parse config.yaml
        id: parse-config
        run: |
          # Find config.yaml in case there're multiple packages
          all_machines=()
          config_files=$(find . -name "config.yaml")

          if [ -z "$config_files" ];then
            # If no config file, all platforms are supported.
            all_machines=("\"qcs6490-rb3gen2-vision-kit\"" "\"qcs9075-rb8-core-kit\"" "\"qcs8300-ride-sx\"")
          else
            for conf_file in $config_files;do
              machines=$(yq '.packages[].machines[].name' ${conf_file})
              all_machines+=("$machines")
            done
          fi

          unique_machines=$(printf '%s\n' "${all_machines[@]}" | sort | uniq)
          echo "Machines:" "${unique_machines[@]}"

          all_machines_json=$(printf '%s\n' "${unique_machines[@]}" | jq -s -c)
          
          echo "machine=${all_machines_json}" >> $GITHUB_OUTPUT
            
  build:
    needs: generate-matrix
    runs-on: [self-hosted, x86]
    timeout-minutes: 720
    strategy:
      fail-fast: false
      matrix: 
        machine: ${{ fromJson(needs.generate-matrix.outputs.machine) }}
        distro:
          - qcom-robotics-ros2-jazzy
    steps:
      - name: Set enviroment variables
        run: |
          echo "MACHINE=${{ matrix.machine }}" >> $GITHUB_ENV
          echo "DISTRO=${{ matrix.distro }}" >> $GITHUB_ENV

      - name: Set up SDK
        run: |
          set -x
          export TARGET_DIR="${PERSIST_DIR}/${MACHINE}-${DISTRO}-${QCOM_SELECTED_BSP}"
          if [ -e ${PERSIST_DIR} ] && [ -r ${PERSIST_DIR} ] && [ -x ${PERSIST_DIR} ];then
            image_dir=$(find ${TARGET_DIR} -type d -name 'qcom-[0-9]*.[0-9]*.[0-9]*-QLI.[0-9]*.[0-9]*-Ver.[0-9]*.[0-9]*_robotics-product-sdk-[0-9]*.[0-9]' | sort -V | tail -n 1)
            sdk_file=$(find ${image_dir} -type f -name "*.sh")
            echo "SDK path: ${image_dir}"
            echo "SDK file: ${sdk_file}"

            echo "Setting up SDK..."
            umask 022
            ${sdk_file} <<EOF
            ${SDK_DIR}
            Y
          EOF
          else
            echo "Shared directory is unavailable!!!"
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/ros_ws/${{ github.event.repository.name }}

      - name: Download dependencies
        run: |
          cd ${WORKSPACE}
          git clone https://github.com/qualcomm-qrb-ros/qrb_ros_interfaces
        
      - name: build
        run: |
          cd ${SDK_DIR}
          umask 022
          . environment-setup-armv8-2a-qcom-linux
          cd ${WORKSPACE}
          export AMENT_PREFIX_PATH="${OECORE_NATIVE_SYSROOT}/usr:${OECORE_TARGET_SYSROOT}/usr"
          export PYTHONPATH=${PYTHONPATH}:${OECORE_NATIVE_SYSROOT}/usr/lib/python3.12/site-packages/:${OECORE_TARGET_SYSROOT}/usr/lib/python3.12/site-packages/

          # Get ROS package list
          packages=$(colcon list)

          # Get ignore list
          ignore_list=()

          while read -r package _ _; do
            cd ${{ github.workspace }}/ros_ws/${{ github.event.repository.name }}/.github/

            if [ -f ./config.yaml ]; then
              machine_supported=$(yq '.packages[] | select(.name == "'"${package}"'") | .machines[] | select(.name == "'"${MACHINE}"'")' ./config.yaml)
              if [ -z "${machine_supported}" ];then
                ignore_list+=("${package}")
              fi
            else
              echo "config.yaml does not exist!"
              ignore_list=()
            fi
          done <<< "$packages"
          echo "Ignore list:" "${ignore_list[@]}"

          cd ${WORKSPACE}
          colcon build --packages-ignore "${ignore_list[@]}" --merge-install --cmake-args \
            -DPython3_ROOT_DIR=${OECORE_TARGET_SYSROOT}/usr \
            -DPython3_NumPy_INCLUDE_DIR=${OECORE_TARGET_SYSROOT}/usr/lib/python3.12/site-packages/numpy/core/include \
            -DPYTHON_SOABI=cpython-312-aarch64-linux-gnu -DCMAKE_STAGING_PREFIX="$(pwd)/install" \
            -DCMAKE_PREFIX_PATH="$(pwd)/install/share" \
            -DBUILD_TESTING=OFF

      - name: Publish artifacts
        continue-on-error: true
        run: |
          build_dir=${PERSIST_DIR}/builds/${GITHUB_RUN_ID}
          mkdir -p $build_dir

          tar -cvf ${build_dir}/${{ github.event.repository.name }}-${MACHINE}-${DISTRO}-${QCOM_SELECTED_BSP}-artifacts.tar --transform "s|^${WORKSPACE}/||" -C ${WORKSPACE} install build log

          ##########################debug###############################
          ls -al  ${build_dir}

          # Instruct our file server to make these files available for download
          url="https://quic-qrt-ros-fileserver-1029608027416.us-central1.run.app/${GITHUB_RUN_ID}/"
          retries=8
          okay=0
          shopt -s lastpipe  # allows us to capture the value of `okay` in the while loop below
          for ((i=0; i<retries; i++)); do
              curl -X POST -H "Accept: text/event-stream" -i --fail-with-body -s -N ${url} | \
                  while read -r line; do
                      echo $line
                      if [[ $line == STATUS=* ]]; then
                          if [[ $line == "STATUS=OK" ]]; then
                              okay=1
                              break
                          fi
                      fi
                  done
              [ $okay -eq 1 ] && break
              echo # new line break in case response doesn't have one
              echo "Error: unable to publish artifacts, sleep and retry"
              sleep 2
          done
          (( retries == i )) && { echo 'Failed to publish artifacts'; exit 1; }
          echo Artifacts available at: ${url}